sudo: false
language: node_js
env:
  - CXX=g++-4.8 CC=gcc-4.8
    before_install:
  - chmod +x /scripts/download
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - libzmq3-dev
node_js:
  - 8
script:
  - ./scripts/download
#  - npm run regtest
  - npm run test
  - npm run jshint
after_success:
  - npm run coveralls
